version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - JOB_TITLES=${JOB_TITLES}
      - KEYWORDS=${KEYWORDS}
    volumes:
      - ./backend/src:/app
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: